// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9SnCPThK6pwYtAWQtvvhjHZW2XkOKwQ',
    appId: '1:486017725620:web:58e9f6546fe1135c2193e1',
    messagingSenderId: '486017725620',
    projectId: 'stomo-track-6050e',
    authDomain: 'stomo-track-6050e.firebaseapp.com',
    storageBucket: 'stomo-track-6050e.appspot.com',
    measurementId: 'G-XXXXXXXXXX' // Add your measurement ID if you have one
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9SnCPThK6pwYtAWQtvvhjHZW2XkOKwQ',
    appId: '1:486017725620:android:58e9f6546fe1135c2193e1',
    messagingSenderId: '486017725620',
    projectId: 'stomo-track-6050e',
    storageBucket: 'stomo-track-6050e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ9SnCPThK6pwYtAWQtvvhjHZW2XkOKwQ',
    appId: '1:486017725620:ios:58e9f6546fe1135c2193e1',
    messagingSenderId: '486017725620',
    projectId: 'stomo-track-6050e',
    iosBundleId: 'com.example.stomotologiyaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ9SnCPThK6pwYtAWQtvvhjHZW2XkOKwQ',
    appId: '1:486017725620:macos:58e9f6546fe1135c2193e1',
    messagingSenderId: '486017725620',
    projectId: 'stomo-track-6050e',
    iosBundleId: 'com.example.stomotologiyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ9SnCPThK6pwYtAWQtvvhjHZW2XkOKwQ',
    appId: '1:486017725620:windows:58e9f6546fe1135c2193e1',
    messagingSenderId: '486017725620',
    projectId: 'stomo-track-6050e',
  );
}
